version: '3.8'

services:
  db-produto-service:
    image: postgres:15
    container_name: gerenciador_de_produtos_db
    environment:
      POSTGRES_DB: gerenciador_de_produtos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5439:5432"

networks:
  default:
    driver: bridge